// engines/complianceEngine.ts

/**
 * Compliance & Accreditation Engine
 * ---------------------------------
 * Governs regulatory language, disclaimers, and alignment
 * across ALL training generated by the platform.
 *
 * This engine:
 * ✅ Prevents false accreditation claims
 * ✅ Supports global jurisdictions
 * ✅ Handles ministry vs industry contexts
 * ✅ Is EXTENDABLE without refactor
 */

export type Jurisdiction =
  | "AU"
  | "NZ"
  | "US"
  | "UK"
  | "GLOBAL";

export type CourseContext =
  | "MINISTRY"
  | "COMMUNITY"
  | "PROFESSIONAL"
  | "INDUSTRY"
  | "ACADEMIC";

export interface ComplianceInput {
  jurisdiction: Jurisdiction;
  context: CourseContext;
  accredited: boolean;
  issuingBody?: string;
}

export interface ComplianceBlock {
  heading: string;
  disclaimer: string;
  alignment?: string;
}

/**
 * MAIN ENTRY POINT
 */
export function buildComplianceBlock(
  input: ComplianceInput
): ComplianceBlock {
  const { jurisdiction, context, accredited, issuingBody } = input;

  if (!accredited) {
    return {
      heading: "Important Notice",
      disclaimer: buildNonAccreditedDisclaimer(jurisdiction, context),
    };
  }

  return {
    heading: "Accreditation & Recognition",
    disclaimer: buildAccreditedDisclosure(jurisdiction, issuingBody),
    alignment: buildAlignmentStatement(jurisdiction, context),
  };
}

/**
 * NON-ACCREDITED DISCLAIMER
 * -------------------------
 * Legally required in many regions (esp. Australia)
 */
function buildNonAccreditedDisclaimer(
  jurisdiction: Jurisdiction,
  context: CourseContext
): string {
  if (jurisdiction === "AU") {
    return `This training is not nationally recognised under the Australian Qualifications Framework (AQF). It is provided for ${context.toLowerCase()} learning and skill development purposes only.`;
  }

  return `This training is not formally accredited. It is provided for educational and development purposes only.`;
}

/**
 * ACCREDITED DISCLOSURE
 */
function buildAccreditedDisclosure(
  jurisdiction: Jurisdiction,
  issuingBody?: string
): string {
  if (jurisdiction === "AU") {
    return `This training is accredited and issued under the authority of ${issuingBody || "an approved issuing body"} in alignment with applicable Australian standards.`;
  }

  return `This training is issued by ${issuingBody || "the issuing organisation"} under the applicable regulatory framework.`;
}

/**
 * ALIGNMENT STATEMENT (NON-LEGAL CLAIM)
 */
function buildAlignmentStatement(
  jurisdiction: Jurisdiction,
  context: CourseContext
): string {
  if (jurisdiction === "AU") {
    if (context === "COMMUNITY" || context === "MINISTRY") {
      return "This program is aligned with relevant Australian community and professional capability frameworks.";
    }

    return "This program is aligned with relevant Australian industry and professional standards.";
  }

  return "This program is aligned with recognised international frameworks and best practices.";
}

/**
 * FUTURE EXTENSIONS (SAFE TO ADD)
 * -------------------------------
 * - Per-unit compliance flags
 * - RTO / Provider ID integration
 * - Government tender alignment
 * - ISO / CPD recognition
 * - Jurisdiction auto-detection
 */
